server:
  port: 8080

app:
  application-context-name: Spring Video Streaming
  application-short-name: SVS
  log-request-http:
    enabled: true
  locale-resolver-languages: vi,en
  log:
    loki:
      host: localhost
      port: 3100
  default-service-enable-log-request: true
  cache:
    redisson:
      enabled: true
      password: 17052002
      node-addresses: redis://localhost:7001,redis://localhost:7002,redis://localhost:7003,redis://localhost:7004,redis://localhost:7005,redis://localhost:7006
      username: default
      connection-pool-size: 16
      master-connection-pool-size: 16
      slave-connection-pool-size: 16
      subscription-connection-pool-size: 10
      connection-minimum-idle-size: 6
      master-connection-minimum-idle-size: 6
      slave-connection-minimum-idle-size: 6
  minio:
    enabled: true
    host: localhost
    port: 10000
    username: didannguyen
    password: 17052002
    secure: false
    bucket:
      video: videos
      hls: hls
  time-trace-enabled: true
  upload:
    temp-dir: /tmp/video-upload
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 1 day
  api:
    key: 1234567890abcdef # Phải giống với key trong worker
  video:
    allowed-formats: video/mp4,video/x-matroska,video/quicktime
    max-file-size: 1073741824 # 1GB
  transcoding:
    profiles:
      - name: 1080p
        width: 1920
        height: 1080
        bitrate: 5000k
      - name: 720p
        width: 1280
        height: 720
        bitrate: 2500k
      - name: 480p
        width: 854
        height: 480
        bitrate: 1000k
      - name: 360p
        width: 640
        height: 360
        bitrate: 500k
  rtmp:
    url: rtmp://localhost/live
  webrtc:
    url: wss://localhost:8443/webrtc
  datasource:
    default:
      enabled: true
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/streaming
      username: didannguyen
      password: 17052002
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true
          format_sql: true
          use_sql_comments: true
      configuration:
        maximum-pool-size: 100
        idle-timeout: 40000
        connection-timeout: 60000
        max-lifetime: 600000


spring:
  application:
    name: stream-video
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  kafka:
    enabled: true
    producer:
      enabled: true
      bootstrap-servers: localhost:9092
      retries: 3
      topic:
        video-uploaded: video-uploaded
        video-processed: video-processed
        livestream-status: livestream-status
    consumer:
      enabled: true
      bootstrap-servers: localhost:9092
      group-id: video-service-group
    bootstrap-servers: localhost:9092

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day

kafka:
  topic:
    video-uploaded: video-uploaded
    video-processed: video-processed
    livestream-status: livestream-status

debezium:
  offset:
    storage:
      file:
        filename: /tmp/streaming/offsets.dat 